language: android
android:
  components:
  - tools
  - platform-tools
install:
  - echo y | sdkmanager "ndk-bundle"
script:
  - curl -u xausky:$SYSKILLER_TOKEN https://syskiller.org/remote.php/webdav/xausky.jks -o ../xausky.jks
  - ./gradlew assembleRelease
deploy:
  skip_cleanup: true
  provider: releases
  draft: true
  api_key:
    secure: b1fhgZQ33nh0DJMQvDBodfJfZK9kFcJXL5MsG2DlZuomZf6+WaCdNNhKIkMofFYkMz719RJXpv6IzfTMu6a/ElRK/1Jf2cyuiqpQR2js98ZNCGOSTEg9e/dGB+9UX8oGz2pRY57iX7qOnlbUpeWIhsc/eiqyPQsfvx5nfb6LaPLf2VijWhxgf8IYH072azbq6zfju6f8UgYy/i8yoq4JaNF3neeohlw0nCxugz4/QUsO64RzH1VdL2Wh5giuw5b+0GwpSX+hl5LeE52RoZ9FkfmXacE8Kk05si4wcL4BorkD0NiDWtaQ1xORX6ZM26TKMCOHQYzZmc+r72Zo0c34Snb0fcKuh/MAMTWPWcBV7rmvqG1E3S+hyQAtQPzs1XIqd1kup678r+18WQGDocCTmPpdIsNsh3GgnwE3/Z2P+W4D33jj+iDhCiWFCYrB68D5MIQNtk9RytOZWc/BM27ByZT8XeyUh0pWhrg0SMbeQrYOLtTsg8MUBnW/RT/yz4fJ7MO1lhAHpmdcep3D/jC+7fnxsqbhLKo6TaX39oEZmPysZAUt5rlnDuxhtH9BvFSVQ1F0eV5EIOTMgMm1dWBlQXbCv9cIzeyDb0y0KLTD9p+gzAwwHPMj2ipusfKTLFy0FASoRxDzQ1c46dN1r69Pfkb3BwgawhkFDn1JmXQc95k=
  file: app/build/outputs/apk/release/app-release.apk
  on:
    tags: true
    repo: xausky/UnityModManager
after_success:
- curl -u xausky:$SYSKILLER_TOKEN -T app/build/outputs/apk/release/app-release.apk https://syskiller.org/remote.php/webdav/模组管理器/模组管理器-$TRAVIS_BRANCH.apk
